version: "3.1"

services:
  mysql:
    image: percona:8.0.15-5-centos
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: xRssWO9PSPhHaR
      MYSQL_DATABASE: default
      LANG: ru_RU.UTF-8
    volumes:
      - ./data:/var/lib/mysql:rw
      - ./migrations:/docker-entrypoint-initdb.d:rw
      - ./db/config:/etc/my.cnf.d
    ports:
      - 3306:3306

